"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files": [
  {
    "source": "/app/src/main/res/values/strings.xml",
    "translation": "/app/src/main/res/values-%android_code%/strings.xml",
    "languages_mapping": {
      "android_code": {
      "de": "de",
      "ru": "ru",
      "fr": "fr",
      "es": "es",
      "it": "it"
      }
    }
  },
  {
    "source": "/fastlane/metadata/android/en-US/full_description.txt",
    "translation": "/fastlane/metadata/android/%locale%/full_description.txt",
    "languages_mapping": {
      "locale": {
      "de": "de-DE",
      "ru": "ru",
      "fr": "fr-FR",
      "es": "es-ES",
      "it": "it"
      }
    }
  },
  {
    "source": "/fastlane/metadata/android/en-US/short_description.txt",
    "translation": "/fastlane/metadata/android/%locale%/short_description.txt",
    "languages_mapping": {
      "locale": {
      "de": "de-DE",
      "ru": "ru",
      "fr": "fr-FR",
      "es": "es-ES",
      "it": "it"
      }
    }
  },
  {
    "source": "/fastlane/metadata/android/en-US/changelogs/*.txt",
    "translation": "/fastlane/metadata/android/%locale%/changelogs/%original_file_name%",
    "languages_mapping": {
      "locale": {
      "de": "de-DE",
      "ru": "ru",
      "fr": "fr-FR",
      "es": "es-ES",
      "it": "it"
      }
    }
  }
]
