name: Crowdin Push
run-name: Crowdin Push - ${{ github.event_name == 'workflow_dispatch' && 'Manual' || 'CI' }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    
jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || !contains(github.event.head_commit.message, 'deprec8/l10n')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push sources
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
